#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SearchPartyXamarinAndroid.Resource", IsApplication=true)]

namespace SearchPartyXamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int cameraLayout = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int imageView1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int mainLayout = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int map = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int myActivityButton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int myButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int myCameraButton = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int myMapButton = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SearchMap = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int cameraActivity = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int closeActivity = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int mapActivity = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int openCamera = 2130968578;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
